### ISSUE TITLE
Quick Start Guide: Divshot Deployment is confusing

### ISSUE THREAD

**Issue by alexisabril** [donejs/donejs#82] opened 2015-10-08 06:51 UTC
_Issue by **[BigAB](https://github.com/BigAB)** from Tuesday Oct 06, 2015 at 20:32 GMT_
_Originally opened as https://github.com/donejs/donejs/issues/173_

---

So I was going through the _quick start guide_ and I found this confusing:

In the **Deploy** section where it describes deploying to divshot it was _not clear_ to me that we would only be deploying our _assets_ to divshot, and my confusion was exacerbated by the terminal:

<pre>
$ donejs deploy
donejs - deploying to 'divshot

Uploading 24 files.
Uploading 14 files.
Finalizing build ... DONE.
Releasing build to 'production' ... DONE.

Application deployed to: 'production'.
<b>You can view your app at the following URL: 'http://donejs-chat-adamlbarrett.divshot.io'</b>
</pre>

...namely the `You can view your app at the following URL: 'http://donejs-chat-adamlbarrett.divshot.io'` part, as of course when I went there, it 404'd.

I think we should take the time, to make it clear we are only deploying our assets there, and our node app would still be required.

We could also mention that we could deploy an html file there as well, and have a non-ssr app up on divshot... but maybe that is confusing the matter.

**Comment by alexisabril** [comment] 2015-10-08 06:51
_Comment by **[daffl](https://github.com/daffl)** from Tuesday Oct 06, 2015 at 20:37 GMT_

---

We could also include production.html and rename it to index.html. Then at least the chat app would technically load when going to that URL (albeit without server-side rendering). I think that would be good because people can actually see their own app in production.
And you are right, we should also mention that we are only deploying the production assets.

@matthewp Can we change bundleAssets to somehow include `production.html` and rename it to `index.html` if configured?

**Comment by alexisabril** [comment] 2015-10-08 06:51
_Comment by **[matthewp](https://github.com/matthewp)** from Tuesday Oct 06, 2015 at 20:41 GMT_

---

The static version won't work unless configured to use hashchange routing.

Good points about the guide language, that should be clarified.

**Comment by alexisabril** [comment] 2015-10-08 06:51
_Comment by **[daffl](https://github.com/daffl)** from Tuesday Oct 06, 2015 at 20:52 GMT_

---

The static version will work you just can't go directly to `/chat` which I think is fine.

**Comment by alexisabril** [comment] 2015-10-08 06:51
_Comment by **[daffl](https://github.com/daffl)** from Tuesday Oct 06, 2015 at 20:53 GMT_

---

There's probably a way to configure Divshot to do that as well.

**Comment by moschel** [comment] 2015-10-30 05:52
Closing because divshot is no longer used, so I think this is out of date. Please reopen if you still think the issue isn't solved.

**Closed as completed by moschel** 2015-10-30 05:52 UTC
Labels: website
