### ISSUE TITLE
donejs init fails if there is a parent node_modules

### ISSUE THREAD

**Issue by matthewp** [donejs/donejs#363] opened 2015-10-28 15:59 UTC
Steps to reproduce:

```
mkdir footest && cd footest
mkdir node_modules
mkdir -p foo/bar && cd foo/bar

donejs init donejs-chat
```

Will fail with a message like:

```
> spawn-sync@1.0.13 postinstall /Users/matthew/Projects/footest/node_modules/donejs-cli/node_modules/yeoman-generator/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

donejs-cli@0.5.4 ../../../node_modules/donejs-cli
├── steal-platform@0.0.4
├── q@1.4.1
├── debug@2.2.0 (ms@0.7.1)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── cross-spawn-async@2.0.0 (lru-cache@2.7.0, which@1.2.0)
├── yeoman-environment@1.3.0 (log-symbols@1.0.2, escape-string-regexp@1.0.3, text-table@0.2.0, untildify@2.1.0, chalk@1.1.1, diff@2.1.3, mem-fs@1.1.0, globby@3.0.1, inquirer@0.11.0, grouped-queue@0.3.0, lodash@3.10.1)
├── yeoman-generator@0.20.3 (read-chunk@1.0.1, detect-conflict@1.0.0, yeoman-welcome@1.0.1, path-exists@1.0.0, path-is-absolute@1.0.0, yeoman-assert@2.1.0, rimraf@2.4.3, text-table@0.2.0, class-extend@0.1.2, xdg-basedir@2.0.0, user-home@2.0.0, mime@1.3.4, dargs@4.0.1, chalk@1.1.1, istextorbinary@1.0.2, nopt@3.0.4, async@1.5.0, run-async@0.1.0, shelljs@0.5.3, cli-table@0.3.1, diff@2.1.3, glob@5.0.15, through2@2.0.0, findup-sync@0.2.1, underscore.string@3.2.2, mem-fs-editor@2.0.4, cross-spawn@2.0.0, pretty-bytes@2.0.1, github-username@2.0.0, dateformat@1.0.11, download@4.4.1, gruntfile-editor@1.1.0, sinon@1.17.2, html-wiring@1.2.0, lodash@3.10.1, inquirer@0.8.5)
└── npm@2.14.8
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn node_modules/.bin/donejs ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
```

**Comment by daffl** [comment] 2015-10-28 16:10
It should fail if there is a parent `package.json`. Maybe we have to check what `npm prefix` is actually doing.

**Comment by matthewp** [comment] 2015-10-28 16:24
https://github.com/donejs/donejs/blob/0ab70c825019f17b4d272fca5b21090e540dafe8/bin/donejs#L13

Is that it?

**Comment by daffl** [comment] 2015-10-28 16:30
Well in the `npm init` case we really have to run `npm prefix` to figure out the root path because NPM will install `donejs-cli` in the parent `node_modules` folder.

Another potentially even better option would be to go up and look for a `node_modules` folder instead of a `package.json`.

**Comment by matthewp** [comment] 2015-10-28 16:36
Why do we have to look for a parent node_modules in the donejs init case? Aren't we always either initing from the current folder or creating a folder and then initing from there?

**Comment by daffl** [comment] 2015-10-28 16:44
`npm install donejs-cli` will install in a parent `node_modules` if it exists. So the assumption that `node_modules/.bin/donejs` is always in the current folder is wrong.

**Comment by matthewp** [comment] 2015-10-28 16:57
Is there a scenario where we want it to install in a parent node_modules?  If not (and I _think_ the answer is not) then if you do an `npm init` before `npm install donejs-cli` it will install in the right place.

**Comment by daffl** [comment] 2015-10-28 17:03
That's annoying because initializing your package.json is exactly what `donejs-cli` is doing, you don't want people to do it twice. I think I have a fix for this anyway.

**Comment by marshallswain** [comment] 2015-10-28 18:48
Related to #207. Kind of.

**Comment by daffl** [comment] 2015-10-28 22:19
@marshallswain I think the fixes I submitted should solve your issue as well.

**Comment by matthewp** [comment] 2015-10-29 21:30
I think this might still be happening :(  I was able to reproduce after releasing 0.5.3.

**Comment by daffl** [comment] 2015-10-29 21:43
I know why. The problem is in https://github.com/donejs/cli/blob/master/bin/donejs#L39. I'll fix and make another release.

**Closed as completed** 2015-10-29 22:38 UTC
Labels: bug
