### ISSUE TITLE
Feature comparison labels don't show on iPhone 6

### ISSUE THREAD

**Issue by tomgreever** [donejs/donejs#602] opened 2016-03-31 12:45 UTC
https://donejs.com/Features.html#section=__Featurecomparison
### On my iPhone 6:

![iphone](https://cloud.githubusercontent.com/assets/326843/14176009/5fbf9bd4-f714-11e5-9c85-f75eea92f083.jpg)
### On Chrome desktop:

![screen shot 2016-03-31 at 7 42 29 am](https://cloud.githubusercontent.com/assets/326843/14175994/50883f90-f714-11e5-9621-1555c3de28cf.png)

**Comment by matthewp** [comment] 2017-02-14 19:08
This is what I get from an iPhone 6 in the simulator. Are you using an iPhone 6 or iPhone 6 Plus?

<img width="487" alt="screen shot 2017-02-14 at 2 06 23 pm" src="https://cloud.githubusercontent.com/assets/361671/22944573/1f8169c4-f2bf-11e6-9da1-31080f151d50.png">

**Comment by chasenlehara** [comment] 2017-04-27 17:46
@imaustink Would you mind checking whether this is still an issue please?

**Comment by chasenlehara** [comment] 2017-05-30 16:43
Closing because I can’t reproduce this issue on my iPhone 7 with iOS 10.3.2

**Closed as completed by chasenlehara** 2017-05-30 16:43 UTC
Labels: p2, bug, needs submitter response
