### ISSUE TITLE
Live reload gets broken after browser refresh

### ISSUE THREAD

**Issue by ilyavf** [donejs/donejs#1064] opened 2018-01-04 18:50 UTC
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

I just generated a new app project with DoneJS@1.1.0. Live reload works well for the 1st time in browser, but when I hit browser refresh it stops working (till I restart DoneJS server).

__Steps to reproduce:__

1. Generate DoneJS app
2. Run `donejs develop`
3. Open `localhost:8080` in browser
4. Refresh browser

![image](https://user-images.githubusercontent.com/1895948/34579241-2b6cd340-f156-11e7-9b7c-9f1db9b4e4bf.png)

Donejs server error:
```
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1019:11)
    at TCP.onread (net.js:608:25)
```

__Expected results:__

Live reload should work after browser refresh.

__Actual results:__

Live reload is broken.

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               | 1.1.0
| node -v                  | 8.6.0
| npm -v                   | 5.5.1
| Browser                 | Chrome 63.0.3239.84
| Operating system | MacOS Sierra

**Comment by matthewp** [comment] 2018-01-04 18:55
Thanks, I'll look at it.

**Comment by matthewp** [comment] 2018-01-04 19:21
The socket now emits an `error` event when the connection gets disconnected. I'm not sure if this is caused by some change in our websocket library `ws`, or a change in Node, or a change in Chrome. Looking more into it to figure out what the best solution is.

**Comment by matthewp** [comment] 2018-01-04 19:32
It looks like if we close the websocket in the `beforeunload` window event it will prevent this error from occurring.

It still feels to me like this should be handled on the server though. Like what will happen if the connection is interrupted for some other reason.

**Comment by matthewp** [comment] 2018-01-04 19:38
I think what I'm going to do is handle the event on the server and check if it is this type of error (connection abuptly ended as the socket not in "open" readyState).

**Comment by matthewp** [comment] 2018-01-04 19:40
Underlying bug: https://github.com/stealjs/steal-tools/issues/912

**Comment by matthewp** [comment] 2018-01-04 19:56
It was caused by a change in `ws`: https://github.com/websockets/ws/issues/1256#issuecomment-352337313
  
And also a bug in Chrome 63.

**Comment by matthewp** [comment] 2018-01-04 21:24
This is fixed by https://github.com/stealjs/steal-tools/releases/tag/v1.10.1

![proof](https://user-images.githubusercontent.com/361671/34584924-a9dd4cc2-f16b-11e7-8263-4599970d33a4.gif)

**Closed as completed by matthewp** 2018-01-04 21:24 UTC
Labels: bug
