### ISSUE TITLE
PMO - Add set.algebra to order model

### ISSUE THREAD

**Issue by justinbmeyer** [donejs/donejs#638] opened 2016-04-21 22:58 UTC
As the set algebra isn't added, the requests for new, preparing, delivery, etc can't be combined.

**Comment by justinbmeyer** [comment] 2016-10-19 22:23
Related: https://github.com/donejs/donejs/issues/633

**Comment by phillipskevin** [comment] 2017-02-08 17:07
Duplicate of https://github.com/donejs/donejs/issues/503.

**Closed as completed by phillipskevin** 2017-02-08 17:07 UTC
Labels: p2, guide
