### ISSUE TITLE
Generated app not starting with node@7.6.0 and npm@5.0.3

### ISSUE THREAD

**Issue by marshallswain** [donejs/donejs#959] opened 2017-06-06 01:56 UTC
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

After creating an application with `donejs add app pwa-test`, when I open the root directory and run `donejs develop`, I get the following error:

![screen shot 2017-06-05 at 7 46 01 pm](https://cloud.githubusercontent.com/assets/128857/26810227/a2f0a850-4a27-11e7-8471-02b2e52b00ce.jpg)

I see that done-serve is in the package.json dependencies, but it's not getting installed into `node_modules/.bin`:

![screen shot 2017-06-05 at 7 53 11 pm](https://cloud.githubusercontent.com/assets/128857/26810397/b0820012-4a28-11e7-8e42-ea69869fbe8e.jpg)

Maybe this is an npm bug.  I'm using `npm@5.0.3` with `node@7.6.0`.

__Steps to reproduce:__

- `npm install -g npm donejs`
- `donejs add app pwa-test`
- `cd-pwa-test`
- `donejs develop`

__Expected results:__

The app should start without a problem.

__Actual results:__

The above error is thrown.

__Environment:__

| Software                | Version
| ------------------ | -------
| donejs -V               | 1.0.0
| node -v                  | 7.6.0
| npm -v                   | 5.0.3
| Operating system | macOS 10.12.5

**Comment by marshallswain** [comment] 2017-06-06 01:57
However, if I delete the `node_modules` folder and the `package.lock.json` and `npm install` again, it works as expected.

**Comment by phillipskevin** [comment] 2017-06-06 14:34
@obaidott can you look into this while you're working on adding Node 8 to CI?

**Comment by matthewp** [comment] 2017-06-06 14:43
My guess is that the way `donejs add app` works is that the new lockfile gets created prevents additional packages from being installed. We might want to use the flag to disable the lockfile (if that is indeed the problem, just a guess here).

**Comment by frank-dspeed** [comment] 2017-06-23 14:56
@matthewp this can be closed can't reproduce error. donejs add app + donejs develop works under node 7.6 even under node 8.1.2

**Comment by matthewp** [comment] 2017-06-23 15:01
Thanks.

**Comment by chasenlehara** [comment] 2017-06-26 18:35
This is still an issue. I just tested with npm 5.0.3 & Node 8.1.2 and I got the same issues as what @marshallswain originally reported.

**Comment by marshallswain** [comment] 2017-06-26 21:07
Looks like others are having this same issue, related to `package.lock.json`: https://codeburst.io/disabling-package-lock-json-6be662f5b97d

It might be a quick easy fix to use `--no-package-lock` during the first `npm install` at https://github.com/donejs/donejs/blob/85650e5359e6d5b52a1406fa1929ee72d4360dd0/lib/cli/cmd-init.js#L29-L34

**Comment by frank-dspeed** [comment] 2017-06-26 21:44
@chasenlehara why do i not get that error? maybe because using yarn right?

**Comment by chasenlehara** [comment] 2017-06-26 21:46
Probably! The original issue makes it pretty clear that npm was being used. Please don’t leave comments saying issues are fixed if you haven’t reproduced the original issue and can confirm it was fixed. 😊

**Comment by frank-dspeed** [comment] 2017-06-26 21:55
@chasenlehara  i reproduced it i runned a donejs app a fresh one  under node 7.6 and 8.1 but i am using docker that means i mount the project dir and then on startup use yarn :)

**Comment by andrejewski** [comment] 2017-06-29 04:57
This has been solved. It took making changes to both donejs/donejs and donejs/cli, but now neither step will create a `package-lock.json` file. In order to close this issue, a donejs/donejs patch release will have to be made with @chasenlehara's #978 changes, the donejs/cli changes are in its v1.0.2.

**Comment by frank-dspeed** [comment] 2017-06-29 06:49
@andrejewski  so you mean
```
npm install -g donejs@^1.0.1
```

**Comment by andrejewski** [comment] 2017-06-29 12:55
@frank-dspeed No, the fix for `donejs` will be released as DoneJS v1.0.1. At which point people can update using `npm install -g donejs` and this issue can be closed.

**Closed as completed** 2017-07-07 18:39 UTC
Labels: p1, bug
